#Workflow name
name: CD Pipeline to AWS
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start Postgresql on Ubuntu
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    - name: Create scheduler user
      run: |
        sudo -u postgres psql --command="ALTER USER postgres WITH PASSWORD 'password';" --command="\du"
    - name: Create parceltrace Database
      run: |
        sudo -u postgres createdb --owner=postgres parceltrace
        PGPASSWORD=password psql --username=postgres --host=localhost --list parceltrace
        
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: target/openapi-spring-1.22.1.jar

#Deploy's job
  deploy:
  #Depends on build's job
    needs: build
    name: Deploy
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        #Download the artifact which was uploaded in the build's job
        uses: actions/download-artifact@v3
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: ParcelTnT
          environment_name: Parceltnt-env
          version_label: ${{github.SHA}}
          region: us-east-1
          deployment_package: openapi-spring-1.22.1.jar
